image: docker:18.09.2

include:
  - template: Dependency-Scanning.gitlab-ci.yml

services:
  - docker:dind

before_script:
  - apk add --no-cache py2-pip
  - pip install --no-cache-dir docker-compose==1.23.2
  - pip install docker-compose
  - docker info
  - docker-compose version

build image(s):
  stage: build
  script:
    - docker-compose build

compose services:
  stage: build
  script:
    - docker-compose up -d
    - docker ps
  after_script:
    - docker-compose down --remove-orphans || true
